# [s3]
# bucket='wcdlabbucket'
# folder='lab2/input/'

# [db]
# host='wcdlab.cislhxldgyzd.us-west-2.rds.amazonaws.com'
# port=3306
# schema='superstore'

[run]
py_script="setup.py"

# [api]
# url='https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add'