hiragana_data = [
    (1, 'あ', 'a'),
    (2, 'い', 'i'),
    (3, 'う', 'u'),
    (4, 'え', 'e'),
    (5, 'お', 'o'),
    (6, 'か', 'ka'),
    (7, 'き', 'ki'),
    (8, 'く', 'ku'),
    (9, 'け', 'ke'),
    (10, 'こ', 'ko'),
    (11, 'さ', 'sa'),
    (12, 'し', 'shi'),
    (13, 'す', 'su'),
    (14, 'せ', 'se'),
    (15, 'そ', 'so'),
    (16, 'た', 'ta'),
    (17, 'ち', 'chi'),
    (18, 'つ', 'tsu'),
    (19, 'て', 'te'),
    (20, 'と', 'to'),
    (21, 'な', 'na'),
    (22, 'に', 'ni'),
    (23, 'ぬ', 'nu'),
    (24, 'ね', 'ne'),
    (25, 'の', 'no'),
    (26, 'は', 'ha'),
    (27, 'ひ', 'hi'),
    (28, 'ふ', 'fu'),
    (29, 'へ', 'he'),
    (30, 'ほ', 'ho'),
    (31, 'ま', 'ma'),
    (32, 'み', 'mi'),
    (33, 'む', 'mu'),
    (34, 'め', 'me'),
    (35, 'も', 'mo'),
    (36, 'や', 'ya'),
    (37, 'ゆ', 'yu'),
    (38, 'よ', 'yo'),
    (39, 'ら', 'ra'),
    (40, 'り', 'ri'),
    (41, 'る', 'ru'),
    (42, 'れ', 're'),
    (43, 'ろ', 'ro'),
    (44, 'わ', 'wa'),
    (45, 'を', 'wo'),
    (46, 'ん', 'n')
    ]





# hiragana_data = [
#     (1, 'あ', 'a', 'audio/a.mp3'),
#     (2, 'い', 'i', 'audio/i.mp3'),
#     (3, 'う', 'u', 'audio/u.mp3'),
#     (4, 'え', 'e', 'audio/e.mp3'),
#     (5, 'お', 'o', 'audio/o.mp3'),
#     (6, 'か', 'ka', 'audio/ka.mp3'),
#     (7, 'き', 'ki', 'audio/ki.mp3'),
#     (8, 'く', 'ku', 'audio/ku.mp3'),
#     (9, 'け', 'ke', 'audio/ke.mp3'),
#     (10, 'こ', 'ko', 'audio/ko.mp3'),
#     (11, 'さ', 'sa', 'audio/sa.mp3'),
#     (12, 'し', 'shi', 'audio/shi.mp3'),
#     (13, 'す', 'su', 'audio/su.mp3'),
#     (14, 'せ', 'se', 'audio/se.mp3'),
#     (15, 'そ', 'so', 'audio/so.mp3'),
#     (16, 'た', 'ta', 'audio/ta.mp3'),
#     (17, 'ち', 'chi', 'audio/chi.mp3'),
#     (18, 'つ', 'tsu', 'audio/tsu.mp3'),
#     (19, 'て', 'te', 'audio/te.mp3'),
#     (20, 'と', 'to', 'audio/to.mp3'),
#     (21, 'な', 'na', 'audio/na.mp3'),
#     (22, 'に', 'ni', 'audio/ni.mp3'),
#     (23, 'ぬ', 'nu', 'audio/nu.mp3'),
#     (24, 'ね', 'ne', 'audio/ne.mp3'),
#     (25, 'の', 'no', 'audio/no.mp3'),
#     (26, 'は', 'ha', 'audio/ha.mp3'),
#     (27, 'ひ', 'hi', 'audio/hi.mp3'),
#     (28, 'ふ', 'fu', 'audio/fu.mp3'),
#     (29, 'へ', 'he', 'audio/he.mp3'),
#     (30, 'ほ', 'ho', 'audio/ho.mp3'),
#     (31, 'ま', 'ma', 'audio/ma.mp3'),
#     (32, 'み', 'mi', 'audio/mi.mp3'),
#     (33, 'む', 'mu', 'audio/mu.mp3'),
#     (34, 'め', 'me', 'audio/me.mp3'),
#     (35, 'も', 'mo', 'audio/mo.mp3'),
#     (36, 'や', 'ya', 'audio/ya.mp3'),
#     (37, 'ゆ', 'yu', 'audio/yu.mp3'),
#     (38, 'よ', 'yo', 'audio/yo.mp3'),
#     (39, 'ら', 'ra', 'audio/ra.mp3'),
#     (40, 'り', 'ri', 'audio/ri.mp3'),
#     (41, 'る', 'ru', 'audio/ru.mp3'),
#     (42, 'れ', 're', 'audio/re.mp3'),
#     (43, 'ろ', 'ro', 'audio/ro.mp3'),
#     (44, 'わ', 'wa', 'audio/wa.mp3'),
#     (45, 'を', 'wo', 'audio/wo.mp3'),
#     (46, 'ん', 'n', 'audio/n.mp3')
# ]
#
